// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tickets.Data;

#nullable disable

namespace Tickets.Data.Migrations
{
    [DbContext(typeof(TicketsDbContext))]
    [Migration("20220510173238_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tickets.Core.Entities.Segments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Airline_code")
                        .HasColumnType("text");

                    b.Property<string>("Arrive_Place")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Arrive_datetime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Birthdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Depart_datetime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Depart_place")
                        .HasColumnType("text");

                    b.Property<int?>("Doc_number")
                        .HasColumnType("integer");

                    b.Property<int?>("Doc_type")
                        .HasColumnType("integer");

                    b.Property<int?>("Flight_num")
                        .HasColumnType("integer");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<bool>("Is_passed")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Operation_place")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Operation_time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Operation_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Passenger_type")
                        .HasColumnType("text");

                    b.Property<string>("Patronymic")
                        .HasColumnType("text");

                    b.Property<string>("Pnr_id")
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .HasColumnType("text");

                    b.Property<int>("Ticket_number")
                        .HasColumnType("integer");

                    b.Property<int?>("Ticket_type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Segments");
                });
#pragma warning restore 612, 618
        }
    }
}
